In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Pokemon.csv")

In [3]:
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [4]:
data.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [5]:
hp_mean = data["HP"].mean()
def set_hp(val):
    if val < hp_mean:
        return "Low HP"
    elif val == hp_mean:
        return "neutral HP"
    else:
        return "High HP"

data['HP High or Low'] = data["HP"].apply(set_hp)

speed_mean = data["Speed"].mean()
def set_speed(val):
    if val < speed_mean:
        return "Low Speed"
    elif val == speed_mean:
        return "neutral Speed"
    else:
        return "High Speed"

data['Speed High or Low'] = data["Speed"].apply(set_speed)

data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,HP High or Low,Speed High or Low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Low HP,Low Speed
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Low HP,Low Speed
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,High HP,High Speed
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,High HP,High Speed
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Low HP,Low Speed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Low HP,Low Speed
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Low HP,High Speed
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,High HP,High Speed
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,High HP,High Speed
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,High HP,High Speed